service:
  name: account

---

spring:
  profiles: stage

service:
  name: stage-account
  
---

spring:
  profiles: dev

service:
  name: dev-account

---

spring:
  profiles: prod

service:
  name: prod-account
